config/routes.rb
Rails.application.routes.draw do

  resources :pools do
    resources :readings, except: [:index], controller: 'pools/readings'
  end
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root "pools#index", as: :authenticated_root
  end

  root "pages#welcome", page: "home"
  get "/pages/:page" => "pages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pool.rb
class Pool < ApplicationRecord

  validates :volume, presence: true

  belongs_to :user
  has_many :readings, dependent: :destroy
end

app/models/reading.rb
class Reading < ApplicationRecord

  validates :datetime, presence: true

  belongs_to :pool
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pools
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/pools/readings_controller.rb
class Pools::ReadingsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_pool
  before_action :set_reading, only: [:show, :edit, :update, :destroy]

  # GET /readings
  # GET /readings.json
  def index
    @readings = @pool.readings.all.sort_by { |reading| reading.datetime }
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
  end

  # GET /readings/new
  def new
    @reading = @pool.readings.new(datetime: DateTime.now.strftime('%Y-%m-%dT%H:%M'))
  end

  # GET /readings/1/edit
  def edit
    if current_user.id != @reading.pool.user_id
      flash[:alert] = "You don't have access to that reading"
      redirect_to @pool
    end
  end

  # POST /readings
  # POST /readings.json
  def create
    @reading = @pool.readings.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to @pool, notice: 'Reading was successfully created.' }
        format.json { render :show, status: :created, location: @reading }
      else
        format.html { render :new }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @pool, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to @pool, notice: 'The reading for ' + @reading.datetime.to_s + ' was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:pool_id])
    end

    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reading_params
      params.require(:reading).permit(:datetime, :ph, :alkalinity, :chlorine, :stabilizer, :pool_id, :airtemp, :watertemp)
    end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools
  # GET /pools.json
  def index
    @pools = current_user.pools.all
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
    @pool = Pool.find(params[:id])
    @readings = @pool.readings
    if current_user.id != @pool.user_id
      flash[:alert] = "You don't have access to that pool"
      redirect_to root_path
    end
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = current_user.pools.new(pool_params)

    respond_to do |format|
      if @pool.save
        format.html { redirect_to @pool, notice: 'Pool was successfully created.' }
        format.json { render :show, status: :created, location: @pool }
      else
        format.html { render :new }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @pool }
      else
        format.html { render :edit }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_url, notice: 'Pool was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:volume, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pool Keeper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
  </head>

  <body>

  <%= render 'shared/navbar' %>
  <div class="container">

    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<div class="jumbotron text-center">
  <% if user_signed_in? %>
      <h1>POOL APP</h1>
      <p>Welcome back <%= current_user.email %></p>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => 'btn btn-large btn-danger' %>
  <% else %>
      <h1>POOL APP</h1>
      <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
      <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
  <% end %>

</div>

app/views/pools/_form.html.erb
<%= form_with(model: pool, local: true) do |form| %>
  <% if pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
      <% pool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= form.label :volume %>
    <%= form.number_field(:volume, class: 'form-control') %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', { class: 'btn btn-default' } %>
  </div>
<% end %>

app/views/pools/edit.html.erb
<h1>Editing Pool</h1>

<%= render 'form', pool: @pool %>

<%= link_to 'Cancel', @pool %>

app/views/pools/index.html.erb
<h1>My Pools</h1>

<table class="table">
  <thead>
    <tr>
      <th>Volume</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pools.each do |pool| %>
      <tr>
        <td><%= pool.volume %></td>
        <td>Freshwater</td>
        <td><%= link_to 'Show', pool %></td>
        <td><%= link_to 'Edit', edit_pool_path(pool) %></td>
        <td><%= link_to 'Delete this Pool', pool, method: :delete, data: { confirm: 'Are you sure you want to delete this pool?  You will loose all of the readings for this pool as well.  This action cannot be undone!' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ Create a New Pool', new_pool_path %>

app/views/pools/new.html.erb
<h1>New Pool</h1>

<%= render 'form', pool: @pool %>

<%= link_to 'Back', pools_path %>

app/views/pools/readings/_form.html.erb
<%= form_with(model: @reading, url: [@pool, @reading], local: true) do |form| %>
  <% if reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= form.label :datetime, 'Date of Reading' %>
    <%= form.datetime_field(:datetime, class: 'form-control col-md-6') %>
  </div>

  <div class="form-group field">
    <%= form.label :ph, 'pH' %>
    <%= form.text_field(:ph, class: 'form-control col-md-6') %>
  </div>

  <div class="form-group field">
    <%= form.label 'Alkalinity (ppm)' %>
    <%= form.number_field(:alkalinity, class: 'form-control col-md-6') %>
  </div>

  <div class="form-group field">
    <%= form.label 'Free Chlorine (ppm)' %>
    <%= form.number_field(:chlorine, class: 'form-control col-md-6') %>
  </div>

  <div class="form-group field">
    <%= form.label 'Stabilizer (ppm)' %>
    <%= form.number_field(:stabilizer, class: 'form-control col-md-6') %>
  </div>

  <div class="form-group field">
    <%= form.label 'Air Temperature (F)' %>
    <%= form.number_field(:airtemp, class: 'form-control col-md-6') %>
  </div>

  <div class="form-group field">
    <%= form.label 'Water Temperature (F)' %>
    <%= form.number_field(:watertemp, class: 'form-control col-md-6') %>
  </div>

    <div class="actions">
      <%= form.submit 'Submit', { class: 'btn btn-default' } %>
    </div>
<% end %>

app/views/pools/readings/_readings_chart.html.erb
<% ph_data = [] %>
<% alkalinity_data = [] %>
<% stabilizer_data = [] %>
<% chlorine_data = [] %>
<% air_temp_data = [] %>
<% water_temp_data = [] %>

<% readings.each do |reading| %>
    <% ph_data << [reading.datetime, reading.ph] %>
    <% alkalinity_data << [reading.datetime, reading.alkalinity] %>
    <% stabilizer_data << [reading.datetime, reading.stabilizer] %>
    <% chlorine_data << [reading.datetime, reading.chlorine] %>
    <% air_temp_data << [reading.datetime, reading.airtemp] %>
    <% water_temp_data << [reading.datetime, reading.watertemp] %>
<% end %>

<div class="card">
  <div class="card-header">
    <h3>Charts</h3>
  </div>
  <div class="card-body">
    <p>View Charts:
      <a href="#ph_chart" data-toggle="collapse" aria-expanded="false" aria-controls="ph_chart">pH</a> |
      <a href="#alkalinity_chart" data-toggle="collapse" aria-expanded="false" aria-controls="alkalinity_chart">Alkalinity</a> |
      <a href="#stabilizer_chart" data-toggle="collapse" aria-expanded="false" aria-controls="stabilizer_chart">Cyanuric Acid</a> |
      <a href="#chlorine_chart" data-toggle="collapse" aria-expanded="false" aria-controls="chlorine_chart">Free Chlorine</a> |
      <a href="#temp_chart" data-toggle="collapse" aria-expanded="false" aria-controls="temp_chart">Air and Water Temps</a> |
      <a href="#all_readings_chart" data-toggle="collapse" aria-expanded="false" aria-controls="all_readings_chart">All Readings Combined</a> |
      <a href=".open_all" data-toggle="collapse" aria-expanded="false" aria-controls="all_readings_chart">Open All Individually</a>
    </p>
    <div class="chart collapse" id="all_readings_chart">
      <%= line_chart [
                             {name: 'pH', data: ph_data},
                             {name: 'Alkalinity', data: alkalinity_data},
                             {name: 'Cyanuric Acid', data: stabilizer_data},
                             {name: 'Free Chlorine', data: chlorine_data},
                             {name: 'Air Temp', data: air_temp_data},
                             {name: 'Water Temp', data: water_temp_data}
                     ],
                     adapter: "highcharts", library: {
                      title: {
                              text: 'All Readings'
                      },
                      subtitle: {
                              text: 'Click on the readings in the legend to toggle them on and off'
                      },
                      xAxis: {
                              labels: {
                                      enabled: true,
                              },
                              crosshair: true
                      },
                      yAxis: {
                              labels: {
                                      enabled: true,
                                      format: '{value}°C'
                              },
                              crosshair: true
                      },
                      legend: {

                      }
              } %>
    </div>

    <div class="chart collapse open_all" id="ph_chart">
      <%= line_chart [
                             {name: 'pH', data: ph_data}
                     ],
                     adapter: "highcharts", library: {
                      title: {
                              text: 'pH'
                      },
                      xAxis: {
                              labels: {
                                      enabled: true,
                              },
                              crosshair: true
                      },
                      yAxis: {
                              title: {
                                      text: 'pH Level'
                              },
                              labels: {
                                      format: '{value}°C'
                              },
                              crosshair: true,
                              floor: 6
                      },
                      legend: {
                              enabled: false
                      }
              } %>
    </div>

    <div class="chart collapse open_all" id="alkalinity_chart">
      <%= line_chart [
                             {name: 'alkalinity', data: alkalinity_data}
                     ],
                     adapter: "highcharts", library: {
                      title: {
                              text: 'Alkalinity'
                      },
                      xAxis: {
                              labels: {
                                      enabled: true,
                              },
                              crosshair: true
                      },
                      yAxis: {
                              title: {
                                      text: 'ppm'
                              },
                              labels: {
                                      enabled: true
                              },
                              crosshair: true,
                              floor: 50
                      },
                      legend: {
                              enabled: false
                      }
              } %>
    </div>

    <div class="chart collapse open_all" id="stabilizer_chart">
      <%= line_chart [
                             {name: 'stabilizer', data: stabilizer_data}
                     ],
                     adapter: "highcharts", library: {
                      title: {
                              text: 'Stabilizer'
                      },
                      xAxis: {
                              labels: {
                                      enabled: true,
                              },
                              crosshair: true
                      },
                      yAxis: {
                              title: {
                                      text: 'ppm'
                              },
                              labels: {
                                      enabled: true
                              },
                              crosshair: true
                      },
                      legend: {
                              enabled: false
                      }
              } %>
    </div>

    <div class="chart collapse open_all" id="chlorine_chart">
      <%= line_chart [
                             {name: 'chlorine', data: chlorine_data}
                     ],
                     adapter: "highcharts", library: {
                      title: {
                              text: 'Free Chlorine'
                      },
                      xAxis: {
                              labels: {
                                      enabled: true,
                              },
                              crosshair: true
                      },
                      yAxis: {
                              title: {
                                      text: 'ppm'
                              },
                              labels: {
                                      enabled: true
                              },
                              crosshair: true
                      },
                      legend: {
                              enabled: false
                      }
              } %>
    </div>

    <div class="chart collapse open_all" id="temp_chart">
      <%= line_chart [
                             {name: 'Air Temp', data: air_temp_data},
                             {name: 'Water Temp', data: water_temp_data}
                     ],
                     adapter: "highcharts", library: {
                      title: {
                              text: 'Air and Water Temperatures'
                      },
                      subtitle: {
                              text: 'Click on the readings in the legend to toggle them on and off'
                      },
                      xAxis: {
                              labels: {
                                      enabled: true,
                              },
                              crosshair: true
                      },
                      yAxis: {
                              title: {
                                      text: 'Temperature (°F)'
                              },
                              labels: {
                                      format: '{value}°C'
                              },
                              crosshair: true,
                              ceiling: 120
                      },
                      legend: {

                      }
              } %>
    </div>
  </div>
</div>

app/views/pools/readings/edit.html.erb
<h1>Editing Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Cancel', @pool %>

app/views/pools/readings/new.html.erb
<h1>New Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Cancel', @pool %>

app/views/pools/readings/show.html.erb
<p>
  <strong>Datetime:</strong>
  <%= @reading.datetime %>
</p>

<p>
  <strong>Ph:</strong>
  <%= @reading.ph %>
</p>

<p>
  <strong>Alkalinity:</strong>
  <%= @reading.alkalinity %>
</p>

<p>
  <strong>Chlorine:</strong>
  <%= @reading.chlorine %>
</p>

<p>
  <strong>Stabilizer:</strong>
  <%= @reading.stabilizer %>
</p>

<p>
  <strong>Air Temp:</strong>
  <%= @reading.airtemp %>
</p>

<p>
  <strong>Water Temp:</strong>
  <%= @reading.watertemp %>
</p>

<%= link_to 'Edit', edit_pool_reading_path(@pool, @reading) %> |
<%= link_to 'Back', @pool %>

app/views/pools/show.html.erb
<div class="card">
  <div class="card-header">
    <h3>My Pool</h3>
  </div>
  <div class="card-body">
    <p class="card-text">Volume: <%= @pool.volume %></p>
    <p class="card-text">Type: Freshwater</p>
    <%= link_to 'Edit', edit_pool_path(@pool) %> |
    <%= link_to 'Back', pools_path %>
  </div>
</div>

<%= render 'pools/readings/readings_chart', readings: @readings %>


<br/>
<div class="readings">
  <h2>Readings</h2>
  <table class="table">
    <thead>
    <tr>
      <th>Date of Reading</th>
      <th>pH</th>
      <th>Alkalinity (ppm)</th>
      <th>Free Chlorine (ppm)</th>
      <th>Cyanuric Acid (ppm)</th>
      <th>Air Temperature (F)</th>
      <th>Water Temperature (F)</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= link_to '+ New Reading', new_pool_reading_path(@pool) %></td>
    </tr>
    <% @readings.each do |reading| %>
    <tr>
      <td><%= link_to reading.datetime, edit_pool_reading_path(@pool, reading) %></td>
      <td><%= reading.ph %></td>
      <td><%= reading.alkalinity %></td>
      <td><%= reading.chlorine %></td>
      <td><%= reading.stabilizer %></td>
      <td><%= reading.airtemp %></td>
      <td><%= reading.watertemp %></td>
      <td><%= link_to 'Delete', [@pool, reading], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "POOL KEEPER", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
            <%= current_user.email %>
          <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">My Profile</a>
          <div class="dropdown-divider"></div>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
</nav>